import jsPDF from "jspdf";
import type { PredictionData } from "./mockPredictions";

export function generatePredictionPDF(
  prediction: PredictionData,
  doctorDecision?: string,
  doctorComments?: string,
  includeFullDetails = false,
  patientName?: string | null
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const addLine = (text: string, fontSize = 10, bold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, pageWidth - 40);
    if (y + lines.length * (fontSize * 0.5) > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, 20, y);
    y += lines.length * (fontSize * 0.5) + 4;
  };

  const addSpacer = (h = 6) => { y += h; };

  // Header
  addLine("MEDILOCKER — Health Prediction Report", 18, true);
  addSpacer(4);
  if (patientName) addLine(`Patient: ${patientName}`, 11, true);
  addLine(`Generated: ${new Date().toLocaleDateString()}`, 9);
  addLine(`Report ID: ${prediction.id}`, 9);
  addSpacer(8);

  // Disease & Stats
  doc.setDrawColor(0, 120, 200);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  addSpacer(6);

  addLine("PREDICTED CONDITION", 12, true);
  addLine(prediction.predicted_disease, 14, true);
  addSpacer(2);
  addLine(`Confidence: ${prediction.confidence}%`);
  addLine(`Risk Level: ${prediction.risk_level.toUpperCase()}`);
  addSpacer(8);

  // Explainability
  addLine("EXPLAINABILITY — Contributing Factors", 12, true);
  addSpacer(2);
  prediction.explainability.forEach((f, i) => {
    addLine(`${i + 1}. ${f.factor} (${f.contribution}%)`, 10, true);
    addLine(`   ${f.description}`);
    addSpacer(2);
  });
  addSpacer(4);

  // Prevention
  addLine("PREVENTION RECOMMENDATIONS", 12, true);
  addSpacer(2);
  prediction.prevention.forEach((p, i) => {
    addLine(`${i + 1}. ${p}`);
  });
  addSpacer(4);

  // References
  addLine("REFERENCES", 12, true);
  addSpacer(2);
  prediction.reference_links.forEach((ref) => {
    addLine(`• ${ref.title} — ${ref.source}`);
    addLine(`  ${ref.url}`, 8);
    addSpacer(2);
  });

  // Doctor feedback (if available and full details requested)
  if (includeFullDetails && doctorDecision) {
    addSpacer(6);
    doc.setDrawColor(0, 120, 200);
    doc.line(20, y, pageWidth - 20, y);
    addSpacer(6);
    addLine("DOCTOR FEEDBACK", 12, true);
    addLine(`Decision: ${doctorDecision.toUpperCase()}`);
    if (doctorComments) {
      addLine(`Comments: ${doctorComments}`);
    }
  }

  // Disclaimer
  addSpacer(10);
  doc.setTextColor(128, 128, 128);
  addLine("DISCLAIMER: This report is generated by an AI prediction system and should not be used as a sole basis for diagnosis. Always consult a qualified healthcare professional.", 8);

  doc.save(`prediction-report-${prediction.predicted_disease.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}
